#!/usr/bin/env python2

import rospy, os, subprocess

if __name__=="__main__":
  rospy.init_node('V_REP')
  vrepPath = os.path.expanduser(rospy.get_param('~path'))
  vrep = vrepPath+"/vrep"
  if( not os.access(vrep, os.F_OK or os.X_OK)):
    rospy.logfatal("V-REP executable missing or not executable: %s"%vrep)
  else:
    scene = rospy.get_param('~scene')
    try:
        plugin = rospy.get_param('~plugin')
    except KeyError:
        plugin = "v_repExtRos"
    plugin="lib"+plugin+".so"
    env = os.environ
    plugins = []
    for dir in os.environ["LD_LIBRARY_PATH"].split(":"):
        if os.access(dir+"/"+plugin, os.F_OK):
            plugins.append(dir+"/"+plugin)
    for file in plugins:
        rospy.loginfo("Found V-REP ROS Plugin at %s"%(file))
    if(len(plugins)==0):
        rospy.logfatal("No V-REP ROS plugin found!")
        os._exit(1)
    if(len(plugins)>1):
        rospy.logfatal("Too many V-REP ROS plugins found!")
        os._exit(1)
    try:
        os.symlink(plugins[0], vrepPath+"/"+plugin)
    except:
        pass
    os.environ["LD_LIBRARY_PATH"]=os.environ["LD_LIBRARY_PATH"]+vrepPath
    rospy.loginfo("Starting V-REP(%s) with scene %s"%(vrepPath+'/vrep', scene))
    rospy.logdebug("Environment:\n%s"%os.environ)
    subprocess.call([vrepPath+"/vrep", scene])
