#!/usr/bin/env python2.7

import rospy, os, subprocess

cmds = {"server":"-s", "client":"-c"}

if __name__=="__main__":
  rospy.init_node("Netem_Test")
  role = rospy.get_param('~role')
  host = rospy.get_param('~host')
  try:
    args = rospy.get_param('~args')
  except KeyError:
    args = ""
  hostname = host.split(":")[0]
  try:
    port = int(host.split(":")[1])
  except ValueError:
    rospy.logfatal("Invalid port %s specified please provide a hostname:port combination"%host.split("1")[1])
    os.exit(-1)
  try:
    cmd = ["iperf3", cmds[role], hostname, "-p", "%i"%port]
    if(args!=""):
        cmd = cmd+args.split()
    rospy.loginfo(cmd)
    subprocess.call(cmd)
  except KeyError:
    rospy.logfatal("Invalid role \"%s\" specified try \"server\" or \"client\""%role)
